spring:
  application:
    name: syncfile

logging:
  config: classpath:logback-spring.xml

file:
  interval: 1000
  suffix: .java,.xml,.md,.zip,.yaml,.yml,.properties,.txt,.kt,.sh,.bat,.png,.gif,.bmp,.jpg,.svg,.webp,.tif,.apng,.pdf
  source:
    path: /Users/hujinfeng/test/

  target:
    path: /Users/hujinfeng/test-t/
