spring:
  application:
    name: syncfile

logging:
  config: classpath:logback-spring.xml

file:
  interval: 1000
#  suffix: .java,.xml,.md,.zip,.yaml,.yml,.txt,.kt
  source:
    path: V:/jinfeng/sync/

  target:
    path: D:/sync/
